### ISSUE TITLE
Update xskillscore to handle NaNs (masked values) directly

### ISSUE THREAD

**Issue by bradyrx** [hdrake/cmip6hack-multigen#18]
I'm currently working on a second `xskillscore` PR that allows for `skipna` in the high level functions. This would mean you don't need to do the `.fillna()` workaround and masks will work.

**Comment by hdrake** [comment]
@bradyrx implemented this in `xskillscore` in https://github.com/raybellwaves/xskillscore/pull/31 and it is now in the default notebook of `cmip6hack-multigen` in https://github.com/hdrake/cmip6hack-multigen/pull/20
