### ISSUE TITLE
Clean up workflow by creating module methods

### ISSUE THREAD

**Issue by hdrake** [hdrake/cmip6hack-multigen#22]
Most of the code right now is just for reading in all of the data and repeating the same processing steps over and over again. Much of this could probably be stuck in module methods.

**Comment by brian-rose** [comment]
I actually started to do that during the hackathon but ended up leaving all the data wrangling in the main notebook for easier presentation during the check in.

We can just create a module `data_wrangling.py` and in each analysis notebook a line like
```
from data_wrangling import load_the_data
dataset = load_the_data()
```

**Comment by hdrake** [comment]
Started doing this branch https://github.com/hdrake/cmip6hack-multigen/pull/30 but needs some more work.

Planning on consolidating so analysis notebooks can look something like:
```python
import data_wrangling as dw

ipcc_dict = dw.load_ipcc(pre_process=xr.Dataset.mean(dim='time'))
obs_dict = dw.load_obs(pre_process=xr.Dataset.mean(dim='time'))
obs_ref = obs_dict['era']

mae_dict = {}
for key, ens in ipcc_dict.items():
    mae_dict[key] = xskillscore.mae(ens, obs_ref, dim=['lat', 'lon'], weights=dw.area)
```
