### ISSUE TITLE
Bias due to non-linearity of surface wind diagnostics

### ISSUE THREAD

**Issue by hdrake** [hdrake/cmip6hack-multigen#26]
Unfortunately, we do not have self-consistent wind velocity / speed diagnostics for all six model generations.

The 'sfcWind' metric, which we have for SAR and TAR, is the monthly-mean surface wind speed < u^2 + v^2 >. This is very different from the wind speed computed from the monthly mean velocity field < u >^2 + < v >^2, which I had been diagnosing from the u and v fields that we have available for FAR, CMIP3, CMIP5, and CMIP6.

We have four options moving forward (which I have ranked in terms of my personal preference):
- ask Naomi to upload `sfcWind` for CMIP3, CMIP5, CMIP6 (could take a while) and show for 5 model generations
- use < u > and < v > for 4 model generations
- abandon wind metrics altogether
- use < u >^2 + < v >^2 (unintutive / nonphysical scalar variable) for 4 model generations

**Comment by hdrake** [comment]
Thoughts @brian-rose @bradyrx?

**Comment by hdrake** [comment]
Perhaps even better is to just use mean sea level pressure (`variable_id = psl`), which I already have for SAR, TAR, CMIP3, CMIP5, CMIP6 and both ERA5 and NCEP reanalyses. Working on implementing this now.

**Comment by brian-rose** [comment]
I'm generally not a fan of unphysical diagnostics...  

I also think that self-consistency of the diagnostics through the generations should be a key feature of this analysis.

I say go with the scalar `psl`. In fact I think we might want to include that even if we also have a solution for wind speed.

**Comment by hdrake** [comment]
Replaced `sfcWind` metric with `psl` metric in PR https://github.com/hdrake/cmip6hack-multigen/pull/28. The only advantage of eventually going back to `sfcWind` is that it is a more readily observed quantity and so it is a more natural choice if we want to compare models against "true" observational products rather than reanalyses.
