### ISSUE TITLE
Add reanalysis or observational fields to serve as reference for skill metric

### ISSUE THREAD

**Issue by hdrake** [hdrake/cmip6hack-multigen#4]
See instructions for scraping ERA5 data for relevant variables here: https://github.com/hdrake/cmip6hack-multigen/tree/master/scripts

**Comment by hdrake** [comment]
See instructions for scraping ERA5 data for relevant variables here: https://github.com/hdrake/cmip6hack-multigen/tree/master/scripts

**Comment by brian-rose** [comment]
I'll look at this today.
